In [16]:
# question 1
import numpy as np
a= np.array([[1,2],[3,4]])
list1 = a.tolist()
print(list1)

[[1, 2], [3, 4]]


In [22]:
# question 2
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.diag(a)
s=0
for i in b:
    s+=i
print(s)

15


In [102]:
# question 3
import numpy as np
A=np.array([[1,2],[3,4]])
x=2
n=np.shape(A)
l=n[0]
c=n[1]
for i in range (0,l):
    for j in range(0,c):
        if A[i,j]> x:
            print(A[i,j])


3
4


In [103]:
# question 4
import numpy as np
A= np.array([[1,2],[3,4]])
B= np.array([[1,1],[1,1]])
n= np.shape(A)
l=n[0]
c=n[1]
C=np.zeros(l*c).reshape(l,c)
for i in range(0,l):
    for j in range(0,c):
        C[i,j]=A[i,j]+B[i,j]
print(C)


[[2. 3.]
 [4. 5.]]


In [92]:
# question 5
import numpy as np
A=np.array([[1,2,3],[4,5,6]])
n=np.shape(A)
l=n[0]
c=n[1]
B=np.zeros(l*c).reshape(l,c)
m=np.mean(A,axis=1)
print(m)
for i in range(0,l):
    for j in range(0,c):
        B[i,j]=A[i,j]-m[i]
print(B)



[2. 5.]
[[-1.  0.  1.]
 [-1.  0.  1.]]
